libbrillo: make type_name_undecorate_unittest depend on dbus
type_name_undecorate_unittest fails to build with USE=-dbus due to a transitive
dependency, so move it to the list of tests that depend on dbus.

In file included from libbrillo/brillo/type_name_undecorate_unittest.cc:7:
In file included from libbrillo/brillo/variant_dictionary.h:11:
In file included from libbrillo/brillo/any.h:26:
In file included from libbrillo/brillo/any_internal_impl.h:15:
libbrillo/brillo/dbus/data_serialization.h:63:10: fatal error: 'dbus/message.h' file not found
#include <dbus/message.h>
         ^~~~~~~~~~~~~~~~
1 error generated.

BUG=none
TEST=unittests build with USE=-dbus

Change-Id: I8919781cb0d4b4a9dcfc94988e302e96afbe5ac8
Reviewed-on: https://chromium-review.googlesource.com/477392
Commit-Ready: Stephen Barber <smbarber@chromium.org>
Tested-by: Stephen Barber <smbarber@chromium.org>
Reviewed-by: Chirantan Ekbote <chirantan@chromium.org>